# Generated by Django 4.2.2 on 2023-06-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('item_title', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN')], default=1, max_length=10)),
                ('content', models.TextField()),
                ('item_price', models.IntegerField()),
                ('soldout', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('item_likes', models.IntegerField(default=0)),
                ('item_image', models.ImageField(upload_to='item/item_img/%Y/%m/%d')),
                ('sales', models.IntegerField(default=0)),
                ('item_content', models.ImageField(upload_to='item/item_content/%Y/%m/%d')),
                ('amount', models.IntegerField(default=0)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='item.category')),
            ],
            options={
                'ordering': ['-create_date', 'id'],
                'index_together': {('id',)},
            },
        ),
    ]
