# Generated by Django 4.2.2 on 2023-07-01 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_likes',
        ),
        migrations.AddField(
            model_name='item',
            name='item_likes',
            field=models.ManyToManyField(blank=True, related_name='item_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
