# Generated by Django 4.2.2 on 2023-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
