# Generated by Django 4.2.2 on 2023-06-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupon_coupon_name'),
        ('common', '0002_alter_member_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='coupon',
            field=models.ForeignKey(default=None, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='coupon.coupon'),
        ),
    ]
