# Generated by Django 4.2.2 on 2023-06-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupon_coupon_name'),
        ('common', '0004_alter_member_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='coupon',
        ),
        migrations.AddField(
            model_name='member',
            name='coupon',
            field=models.ManyToManyField(to='coupon.coupon'),
        ),
    ]
