# Generated by Django 4.2.2 on 2023-07-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_member_coupon_member_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
