# Generated by Django 4.2.2 on 2023-06-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
