# Generated by Django 4.2.2 on 2023-07-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
